# Array Operations

In [1]:
import numpy as np

# Arithmetic Operations

In [2]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [4]:
#to add 2 arrays
a1+a2    # this  will only works if the size of both the array are same. if the sizes are different then it will give error of broadcast

array([ 7,  9, 11, 13, 15])

In [5]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1-a2

array([-5, -5, -5, -5, -5])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1//a2

array([0, 0, 0, 0, 0])

In [9]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

# Broadcasting

In [11]:
l=[10,20,30,40]
arr=np.array(l)
arr

array([10, 20, 30, 40])

In [12]:
for i in l:
    print(i+10)

20
30
40
50


In [14]:
#to write the above code, in short way
arr+10                           #This is how broadcasting works(if i have single element and want that element to be added to each and every element of an array,we use broadcasting)

array([20, 30, 40, 50])

In [15]:
#we can do this in the matrix also 
ar1=np.arange(1,26).reshape(5,5)
ar1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
ar1+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

# Deep and shallow Copy

In [17]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [22]:
a   
# we see that on changing on the slice, we are not seeing any change in the original array.But when we do the same thing with the list,it will change the original array as well. 
#what array does, it makes another space in the ram.that's why changing on that array does not change the original array.
#this is a concept of shallow copy.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#when on changing anything on the slice, will change the original array also, that concept is called deep copy.

In [24]:
a
b=a

In [25]:
b[0]=90
b

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
a  #here we see the concept of deep copy. a also changes on changing b

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#a
#b=a
#if we want to make this code as shallow copy we can do by using .copy()

In [28]:
a
b=a.copy()    #on using .copy(), it will follow the shallow copy.on changing b it will not change a

In [29]:
b[0]=30
b

array([30,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
a

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Matrix Operations

In [32]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [33]:
A

array([[1, 2],
       [3, 4]])

In [34]:
B

array([[5, 6],
       [7, 8]])

# MULTIPLICATION

In [35]:
A*B   
#this will multiply normally and give results, but this is not the way how the real matrix multiplication works

array([[ 5, 12],
       [21, 32]])

In [36]:
#To perform matrix multiplication,we use @ instead of *
A@B

array([[19, 22],
       [43, 50]])

In [38]:
#or we can use
np.dot(A,B)

array([[19, 22],
       [43, 50]])

# TRANSPOSE

In [ ]:
#Here we use .T to transpose the array, change rows to columns and columns to rows

In [39]:
A.T

array([[1, 3],
       [2, 4]])

# Advance Array Manipulation

# STACKING ARRAY

Stacking means join two array. But we cannot stacked 2 matrix,because they are already stacked.
we can stack 2 arrays or we can stack 2 vectors
Remember, we have to use vectors and not matrix

In [40]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [44]:
#we can stack arrays in 2 ways
#1.vertical stack
#2.Horizontal stack

In [42]:
np.vstack((a,b))    #This is vertically stack,here elements gets joint horizontally

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
np.hstack((a,b))   #this is horizontally stack,here elements gets joint horizontally

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
np.column_stack((a,b))  #This is a column stack

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Splitting Array

In [47]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
#we can split the arrays in 2 ways
#1.Horizontal split
#2.vertical split

In [49]:
np.hsplit(c,2) 
#It will split c, horizontally in 2 parts 
#we can split the array in equal divisions. As there is 4*4 matrix, then we can split the array either in 2 or 4

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [50]:
np.hsplit(c,3)   #this will give error, as 3 is no an equal division

ValueError: array split does not result in an equal division

In [51]:
np.hsplit(c,4) 

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [52]:
np.vsplit(c,2)  #this is vertically split. and same concept of equal divisions goes here

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]