In [2]:
import numpy as np

1. NumPy arrays are used to store large amounts of numbers.
2. An index is an element’s position in an array. NumPy arrays are 0-indexed.
3. Slicing is where we can access parts of a sequence with name[start:end].
4. 2D arrays have 1D arrays as elements.

# Numpy indexing and slicing of vectors

In [3]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#INDEXING

In [4]:
arr[4]   #it will give 15 because in numpy,arrays are 0-based index

np.int64(15)

In [5]:
arr[8]

np.int64(19)

#SLICING   --> It starts from the start index (inclusive) and ends before the end index (non-inclusive).

In [6]:
arr[1:5]   #it will print numbers from index 1 to index 4. 

array([12, 13, 14, 15])

In [8]:
arr[:5]  #here starting value automatically get set default to 0

array([11, 12, 13, 14, 15])

In [9]:
arr[:]  #it will print the entire array

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[3::2] #here 2 is the step size,it will print elements from 3 to 20 with step size of 2 between each and every element

array([14, 16, 18, 20])

# Numpy indexing and slicing of matrix

In [12]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

#INDEXING

In [13]:
arr[0] #it will print the entire 0th row

array([1, 2, 3, 4, 5])

In [14]:
arr[0,1]  #it will print the element present in 0th row and 1st column

np.int64(2)

In [15]:
arr[5,4]

np.int64(30)

#SLICING

In [18]:
arr[0:2,1:3]      #it will slice the row from 0th to 1st row and slice the column from 1st to 2nd column

array([[2, 3],
       [7, 8]])

In [19]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [20]:
# to select the column
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [30]:
#Finding average
avg=np.average(arr)     #to find average we write it as np.average
avg

np.float64(16.0)

# Boolean Indexing

In [26]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
bool_index=arr%2==0     #if we want all even numbers present inside the matrix,we can do this instead of usig for loop
bool_index
#it will return true and false for each and every element

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [28]:
arr=arr[bool_index]
arr
#here after passing the bool_index to array, it will give those values of matrix only which is giving true.

array([12, 14, 16, 18, 20])