# Introduction

Notebook:  A notebook is a file that contains a set of cells. Each cell can store and run code. Any output will be printed out right below the cell.
There are many flavors of this, Jupyter Notebook and Google Colab are the two popular ones used by academic and industry data analysts.

In python there is no arrays, to solve this issue Jim Hugunin created Numeric library.this library provided array support but the performance is not so much supported. to resolve this
another library created by space telescope science institute and named it as numarray.They want to increase the power of the earlier created library but last array was not compatible with numarray.
Then at 2005 Travis Oliphant merged numeric library and numarray and created new library and named it as Numpy.
Numpy is written in C which are compiled and super fast. This is the main reason Numpy is up to 50x faser than python list.

NumPy (short for "Numerical Python") is a Python library that supports large, multi-dimensional arrays. It also comes with a bunch of math functions that you can use to operate on these arrays.
It works well with other data science libraries such as Pandas (data analysis), Matplotlib (data visualization), and scikit-learn (machine learning), which makes NumPy the obvious first stop in the journey.


In [39]:
#To find the version of the numpy, we write
np.__version__

'2.2.4'

# NumPy Arrays

An array is the core data structure of the NumPy package. It’s a grid of values.

When we see the difference between Python list and Numpy array we see that
1. Data Type== list allows mixed type of data . but in numpy same data type should only be there
2. Performance== list is slower while numpy array is much faster
3. Memory efficiency== list has low while numpy array has high
4. Vector operations== list has manual loops while numpy array has easy and fast operations
So when you have a handful of items, lists are great. But when dealing with thousands or even millions of numbers, NumPy arrays are the way to go!

In [1]:
#importing numpy
import numpy as np

In [2]:
# basic array creation --> we create a numpy array using the list only 
arr=np.array([1,2,3,4])
arr                     

array([1, 2, 3, 4])

In [4]:
a=[1,2,3,4,"hello"]   # we can see the difference between the output of arr and a
a # this is simple array

[1, 2, 3, 4, 'hello']

In [5]:
np.array(a)    #on converting a which is containing diferent data type to numpy array will make all the elements of the a to string type. bcz numpy array contains same data type of elements

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [6]:
# Matrics
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)    #we see a 2d matrix.1d is vector. and matrix greater than 2d is tensorflow

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Generation function

In [11]:
#first type
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#second type-->it will generate zeros
arr=np.zeros((4,8))   #4 rows and 8 columns
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
#third type
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#linear spacing
arr=np.linspace(1,5,3)   #it means we want 3 elements between 1 and 5 and we see that all 3 elements will have equal or linear space in between of them.
arr

array([1., 3., 5.])

# Random Generation function

In [16]:
#NORMALIZATION
np.random.rand(5) 
#we see it gives 5 random number greater than 0. this is a concept of normalization in statistics
#when we get value between 0 and 1, its called normalization, and when we get the value between 3 and -3,its called standardization 

array([0.61896145, 0.69898255, 0.68626781, 0.33196296, 0.82027611])

In [17]:
#STANDARDIZATION
np.random.randn(10) # it will give random numbers between -3 and 3

array([ 1.05172396, -0.89243406,  0.89324408, -0.42458208, -0.1107874 ,
        0.47115363,  0.48161744,  0.10211164,  0.79120175, -1.10958116])

In [19]:
# when we want to generate array of random numbers
np.random.randint(10,20,10) #it will generate array between 10 and 20 with 10 elemets inside it

array([10, 10, 10, 10, 12, 19, 13, 16, 11, 18], dtype=int32)

# Array Attributes

In [21]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.shape     
#on writing attribute,we don't write () after shape. in method we write shape(), but on writing attribute we don't write brackets after it
#it will give (3,3) which means 3 rows and 3 columns

(3, 3)

In [23]:
arr.size

9

In [24]:
arr.dtype

dtype('int64')

# Array methods

In [25]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.min()

np.int64(1)

In [27]:
arr.max()

np.int64(9)

In [28]:
arr.sum()

np.int64(45)

In [29]:
# to find the sum for row or column(axis=0-->column)
np.sum(arr,axis=0)   #when we write axis=0,it provides the sum for a column

array([12, 15, 18])

In [30]:
np.sum(arr,axis=1) #when we write axis=0,it provides the sum for a row
#(axis=1-->row)

array([ 6, 15, 24])

In [31]:
arr.mean()

np.float64(5.0)

In [32]:
arr.std()

np.float64(2.581988897471611)

In [33]:
arr.argmax()   #it gives index of the maximum element

np.int64(8)

In [34]:
arr.argmin()  #it gives index of the minimum element

np.int64(0)

# Reshaping and resizing

In [35]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

It's a 1d vector, if we want to convert it into 2d matrix, then we use method and that is reshape()
in that we provide number of rows and no. of columns and we should remember that the number
of elements in 1d vector should be same to the reshape matrix 
example: 6*5=30  and 1-31=30 both are same. then it will work

In [36]:
arr.reshape(6,5)  # it wil reshape the vector arr into 6 rows and 5 columns. 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [38]:
#resize means we will save the reshape array into the array
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])